# -----------------------------
# Build stage
# -----------------------------
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy solution and restore first (cache friendly)
COPY *.sln .
COPY src/ ./src/
COPY tests/ ./tests/


RUN dotnet restore

# Publish in Release mode
RUN dotnet publish src/ServiceName.Api/ServiceName.Api.csproj \
    -c Release \
    -o /app/publish \
    /p:UseAppHost=false

# -----------------------------
# Runtime stage
# -----------------------------
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet", "ServiceName.Api.dll"]
